language: go

go: 1.2

addons:
    postgresql: "9.3"

before_script:
    - psql -c 'create database tablestruct_test;' -U postgres

before_install:
    - psql --version

script:
    env PGUSER=postgres go test -v
